"""table mod

Revision ID: 74bc68755736
Revises: 656888ffd92a
Create Date: 2024-02-17 11:02:29.624510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74bc68755736'
down_revision: Union[str, None] = '656888ffd92a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'birthday',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_unique_constraint(None, 'contacts', ['mail'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='unique')
    op.alter_column('contacts', 'birthday',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
