"""Init

Revision ID: d97c6d76f881
Revises: 
Create Date: 2024-02-14 18:56:40.478793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd97c6d76f881'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('note_m2m_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('notes', sa.Column('title', sa.String(length=50), nullable=False))
    op.add_column('notes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('notes', 'description',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=150),
               nullable=False)
    op.drop_index('ix_notes_id', table_name='notes')
    op.drop_column('notes', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index('ix_notes_id', 'notes', ['id'], unique=False)
    op.alter_column('notes', 'description',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=250),
               nullable=True)
    op.drop_column('notes', 'created_at')
    op.drop_column('notes', 'title')
    op.drop_table('note_m2m_tag')
    op.drop_table('tags')
    # ### end Alembic commands ###
